Show all asset from registry
galacticcouncil/Basilisk-ui pull request #308
Opened 2023-02-09 10:43 UTC by vkulinich-cl

Fixes #300 
- Fix styling for the redeposited farms on mobile view
- Disable Transfer and Set fee asset payment buttons for the asset without balance

2023-02-10 07:33 UTC, green-jay commented
button should be off by default (all assets not shown)

2023-02-14 11:31 UTC, jak-pan commented
Is this g2g?

2023-02-14 13:28 UTC, vkulinich-cl commented
> Is this g2g?

I'd say yes

2023-02-14 16:57 UTC, jak-pan approved these changes

2023-02-14 17:48 UTC, jak-pan commented
Actually. The assets should have been shown because you can buy them from this screen.

2023-02-14 17:48 UTC, jak-pan commented
Can u pls change it back and merge?

2023-02-14 20:50 UTC, tomashapl1 requested changes
Just small change, rest is OK 👏

2023-02-14 20:50 UTC, tomashapl1 commented on src/sections/wallet/assets/table/WalletAssetsTable.utils.tsx
> +          onTransferClick={
```
() => {
    if(!row.original.total.isZero()) {
        actions.onTransfer(row.original.id)
    }
}
```

2023-02-15 07:36 UTC, green-jay commented
> Actually. The assets should have been shown because you can buy them from this screen.

based it on current prod hdx ui. should be aligned in either case imho

2023-02-15 09:07 UTC, tomashapl1 approved these changes

2023-02-15 12:46 UTC, merged