Show my positions fix
galacticcouncil/Basilisk-ui pull request #325
Opened 2023-02-13 14:55 UTC by vkulinich-cl

Fixes #307 
Fixes #312

2023-02-13 16:24 UTC, vgantchev commented on src/i18n/locales/en/translations.json
> +  "pools.emptyState.description2": "Ape in (DYOR) and earn some rewardssss...",
Join a farm and earn rewards

2023-02-14 09:17 UTC, tomashapl1 requested changes
Just small change 😉

2023-02-14 09:17 UTC, tomashapl1 commented on src/sections/pools/PoolsPage.tsx
> +        ) : data?.length ? (
```
!!data?.length
```

2023-02-14 09:20 UTC, vkulinich-cl commented on src/i18n/locales/en/translations.json
> +  "pools.emptyState.description2": "Ape in (DYOR) and earn some rewardssss...",
@vgantchev so, we are agreed on 'Join a farm and earn rewards'? or you want to make changes based on the @jak-pan comment?

2023-02-14 10:04 UTC, jak-pan commented on src/i18n/locales/en/translations.json
> +  "pools.emptyState.description1": "You have no active farm positions",
```suggestion
  "pools.emptyState.description1": "You have no active positions",
```

2023-02-14 11:26 UTC, jak-pan commented on src/i18n/locales/en/translations.json
>    "pools.emptyState.description2": "Ape in (DYOR) and earn some rewardssss...",
```suggestion
  "pools.emptyState.description2": "Provide liquidity to support the protocol",
```

2023-02-14 11:27 UTC, jak-pan commented on src/i18n/locales/en/translations.json
>    "pools.emptyState.description2": "Ape in (DYOR) and earn some rewardssss...",
We can change this wording later. We should have a warning / explanation everywhere about the risks of LPing. Until then I would not go aggresive.

2023-02-14 16:56 UTC, jak-pan approved these changes

2023-02-14 20:18 UTC, jak-pan commented
LGTM

2023-02-14 20:52 UTC, tomashapl1 requested changes

2023-02-14 20:52 UTC, tomashapl1 commented on src/i18n/locales/en/translations.json
> +  "pools.emptyState.description1": "You have no active positions",
I would prefer naming like:

`pools.emptyState.title` and `pools.emptyState.description`

2023-02-15 08:08 UTC, vkulinich-cl commented on src/i18n/locales/en/translations.json
> +  "pools.emptyState.description1": "You have no active positions",
but both of them are description strings. There is no name, just description

2023-02-15 08:13 UTC, tomashapl1 commented on src/i18n/locales/en/translations.json
> +  "pools.emptyState.description1": "You have no active positions",
OK, so go with `<br />`

```
You have no active positions <br /> Provide liquidity to support the protocol
```

2023-02-15 08:26 UTC, tomashapl1 approved these changes

2023-02-15 08:47 UTC, merged