Reworked APR
galacticcouncil/Basilisk-ui pull request #343
Opened 2023-02-23 09:45 UTC by vkulinich-cl

2023-02-28 07:51 UTC, dqbd requested changes
Za mě krom těchto menších nitpicků 👍 , good job 😄

2023-02-28 07:51 UTC, dqbd commented on src/sections/pools/pool/shares/deposit/PoolSharesDeposit.tsx
>            <PoolSharesDepositFarm pool={pool} depositNft={depositNft} />
<img width="492" alt="CleanShot 2023-02-28 at 08 42 07@2x" src="https://user-images.githubusercontent.com/1443449/221786992-1a800dbb-264c-49c4-83f6-50262f4af4fa.png">

Není zarovnané s obsahem, viz design

2023-02-28 07:51 UTC, dqbd commented on src/sections/pools/pool/shares/deposit/PoolSharesDepositFarm.tsx
> +import { useAssetMeta } from "../../../../../api/assetMeta"
_discussion_: jaký editor používáš? editor by měl používat absolutní importy při našeptávání

2023-02-28 07:51 UTC, dqbd commented on src/sections/pools/farm/loyaltyGraph/PoolJoinFarmLoyaltyGraph.worker.ts
>        //reduce the number of periods by taking one period each 3000 periods
_nit_: tenhle komentář už se nevztahuje ke kódu

2023-02-28 08:37 UTC, dqbd requested changes

2023-02-28 08:37 UTC, dqbd commented on src/utils/farms/apr.ts
> +          .unwrap()
Co když bude `loyaltCurve` None? Pokud se nepletu, loyaltyCurve je Option

2023-03-01 08:03 UTC, vkulinich-cl commented on src/sections/pools/farm/detail/PoolFarmDetail.tsx
> +          <>
we need this fragment, since it's a conditional rendering of two components

2023-03-01 08:07 UTC, vkulinich-cl commented on src/sections/pools/pool/shares/deposit/PoolSharesDepositFarm.tsx
> +import { useAssetMeta } from "../../../../../api/assetMeta"
pouzivam VS Code, ale to se obcas stane, zalezi na tom jakym zpusobem si to naimportuji. Budu to hlidat

2023-03-01 08:08 UTC, vkulinich-cl commented on src/sections/pools/farm/loyaltyGraph/PoolJoinFarmLoyaltyGraph.worker.ts
>        //reduce the number of periods by taking one period each 3000 periods
vztahuje, udelal jsem tam zmenu :)

2023-03-01 11:38 UTC, dqbd requested changes

2023-03-01 11:38 UTC, dqbd commented on src/utils/farms/apr.ts
> +  if (!loyaltyCurve) return 0
Neměl by `loyaltyCurve` v případě `null` být 1?

2023-03-06 12:29 UTC, dqbd approved these changes

2023-03-06 12:29 UTC, merged